### ISSUE TITLE
Rare recommendation/ad

### ISSUE THREAD

**Issue by dayanch96** [PoomSmart/YouTube-X#1]
Got only once recommendation from 'brand_promo.view' and it looks like this:

![2023_02_17_15_25_IMG_7809](https://user-images.githubusercontent.com/38832025/229261179-bf146e9a-dbef-4a2a-a702-2ea85ef71653.JPG)
 
Just in case if it can be useful

**Comment by PoomSmart** [comment]
Try compiling the latest build from here and see if it works.

**Comment by dayanch96** [comment]
I have it rarely and only when I use Turkish localization. It seems to work

**Comment by dayanch96** [comment]
more ads that appears in search results
"eml.video_display_full_layout" (can be found by searching 'Amazon' or 'ebay' etc.) 
"eml.feed_ad_metadata" (can be found by searching 'Tell me why')

**Comment by PoomSmart** [comment]
@dayanch96 Couldn't find it myself. Screenshots? And is it as simple as adding those IDs to the existing check in the tweak?

**Comment by dayanch96** [comment]
> is it as simple as adding those IDs to the existing check in the tweak?

No, but reverting (NSData *)elementData method for YTIElementRenderer fixes it.

Also, adding statement_banner (same issue with shorts videos) loads an empty block on its place. In my case, removing it through YTAsyncCollectionView works properly (Example: https://github.com/MiRO92/YTNoShorts/blob/main/Tweak.xm#L5)
tested on jailbroken iphone 7, running iOS 15.6 and jailed 11, iOS 15.6.1

![IMG_4440](https://github.com/PoomSmart/YouTube-X/assets/38832025/8ef3b371-e806-4d44-bca9-601f76890e9f)

**Comment by PoomSmart** [comment]
Yeah, hooking the cell at item method directly seems to be the surest way - but does this lead to any intermittent app crashing?

**Comment by dayanch96** [comment]
> does this lead to any intermittent app crashing?
Haven't faced yet in two weeks of use

**Comment by PoomSmart** [comment]
@dayanch96 Take a look at my PR.

I have doubts about `video_display_full_layout` though. The name is too generic to be an ad.

https://github.com/PoomSmart/YouTube-X/pull/3

**Comment by dayanch96** [comment]
feed_ad_metadata still appears but not video_display_full_layout (its promoted YT Videos + redirect to site button on some of them)

i assuming that issue in using isAd bool since changing it back to directly hooking YTIElementRenderer (as here: https://github.com/PoomSmart/YouTube-X/blob/f9c9225709723409282057b49639fbeb321ddd8e/Tweak.x#L40-L44) solves issue with eml.video_display_full_layout" and "eml.feed_ad_metadata"

**Comment by PoomSmart** [comment]
Try 1.4.0

**Comment by dayanch96** [comment]
Works as expected. Thanks

**Comment by dayanch96** [comment]
@PoomSmart, hey. App updated and old ads appears again (Search '4k video', for example). Guess this part necessary to keep it removed

```
%hook YTIElementRenderer
- (NSData *)elementData {
    if (self.hasCompatibilityOptions && self.compatibilityOptions.hasAdLoggingData) return nil;
}
%end
```

**Comment by PoomSmart** [comment]
Added in 1.4.2
