### ISSUE TITLE
Sideloading

### ISSUE THREAD

**Issue by indrapalijama** [PoomSmart/YouTube-X#11]
hi pom!
can i sideload this tweak? for non-jailbreak user, thanks

**Comment by dayanch96** [comment]
You can. Build it for rootful jb, or download arm.deb and inject in your app before sideloading

**Comment by oldman20** [comment]
> You can. Build it for rootful jb, or download arm.deb and inject in your app before sideloading

where to download deb? is it has arm64.deb architect?

**Comment by indrapalijama** [comment]
> You can. Build it for rootful jb, or download arm.deb and inject in your app before sideloading

when i use theos using this command `make package`
i got this error instead
"YouTubeHeader/YTIElementRenderer.h' file not found", do you have any suggestions on how to fix this?
