### ISSUE TITLE
1.6.7 causing blank thumbnail issues

### ISSUE THREAD

**Issue by mblend27** [PoomSmart/YouTube-X#8]
Issue: After updating to YouTube X 1.6.7 the YouTube app stops showing videos when I scroll down (blank instead of thumbnails).

Solution: Downgrading YouTube X to 1.6.6 fixed the bug 🤷‍♂️

Me: iPhone 13 mini - iOS 16.1.1 - YouTube 19.24.3

Note: I’m using uYou 3.0.4 for other features - could be a variable.

https://www.reddit.com/r/jailbreak/s/QIxMnwUFFj

**Comment by PoomSmart** [comment]
Fixed
